options:
  aci-repo:
    type: string
    default: 'deb http://a.b.c.d'
    description: "Apt repository for ACI module"
  aci-repo-key:
    type: string
    default:
    description: "Repo key, if missing no package authentication will be performed"
  aci-opflex-debug-level:
    type: string
    default: 'debug'
    description: "Debug level"
  aci-apic-system-id:
    type: string
    default:
    description: "id string for this openstack instance"
  aci-encap:
    type: string
    default: vxlan
    description: "vlan or vxlan"
  aci-infra-vlan:
    type: int
    default: 4093
    description: "ACI infra vlan"
  aci-opflex-peer-ip:
    type: string
    default: '10.0.0.30'
    description: "Opflex peer ip on ACI."
  aci-opflex-remote-ip:
    type: string
    default: '10.0.0.32'
    description: "Opflex remote ip"
  aci-uplink-interface:
    type: string
    default:
    description: ""
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access RabbitMQ queue
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ vhost
